Upload tensor CASSI implementation
pycolibri/pycolibri pull request #115
Opened 2024-03-28 21:21 UTC by Enmartz

2024-04-19 19:18 UTC, David-Morales-Norato commented on colibri_hdsp/optics/tensorial.py
> +    y = torch.zeros(b, S, M, N + L - 1).to(x.device)
ajsdhf

2024-04-22 13:53 UTC, Enmartz commented
I update the scripts following the suggestions, please review them again, thanks.

2024-05-20 20:29 UTC, bemc22 commented
please include the tests workflow from the main branch

2024-08-23 19:08 UTC, David-Morales-Norato commented
Any news about this PR? @Enmartz

2024-09-27 12:59 UTC, Enmartz commented
> Any news about this PR? @Enmartz

Yes, I update the implementation according to the last version of the repository, please review this with @yromariogh.

2025-03-16 23:50 UTC, bemc22 commented on colibri/optics/tensor_cassi.py
This file present a lot of incorrect rendering of equation when running `make html`

2025-03-16 23:51 UTC, bemc22 commented on examples/demo_tensor.py
you set torch.float64 as default dtype, this generate problems since the standard its float32, corrected.

2025-03-16 23:51 UTC, bemc22 requested changes
please update the docs for TensorCASSI

2025-03-25 15:52 UTC, bemc22 commented on colibri/optics/tensor_cassi.py
> +            self.sensing = forward_tensor_cassi
the `forward_tensor_cassi` its the same `forward_sd_cassi`

2025-03-25 15:54 UTC, bemc22 commented on colibri/optics/tensor_cassi.py
> +class TensorCASSI(torch.nn.Module):
After review, i consider that `TensorCASSI` should be implemented as a particular optimized solver for the `SD_CASSI` class instead of a new imaging class.

2025-03-25 15:56 UTC, bemc22 commented on examples/demo_tensor.py
> +sys.path.append(os.getcwd())
this line should go before import `colibri`

2025-03-25 16:01 UTC, bemc22 commented on colibri/optics/functional.py
> +        y[..., k:N + k] += + y_noshift[:, k]
`+= +` ?, is it okey?

2025-03-25 16:08 UTC, bemc22 commented on colibri/optics/functional.py
> +    return y1
this backward its a little strange, why you sum over channels, its not the same that sd_cassi backward?

2025-03-29 21:28 UTC, Enmartz commented on colibri/optics/tensor_cassi.py
> +class TensorCASSI(torch.nn.Module):
How do you propose implementing this? What would the structure be?

2025-03-29 21:29 UTC, Enmartz commented on examples/demo_tensor.py
> +sys.path.append(os.getcwd())
Solved

2025-03-29 21:37 UTC, Enmartz commented on colibri/optics/tensor_cassi.py
Solved

2025-03-29 21:41 UTC, Enmartz commented on colibri/optics/functional.py
> +        y[..., k:N + k] += + y_noshift[:, k]
It was a typo, fixed

2025-03-29 21:47 UTC, Enmartz commented on colibri/optics/functional.py
> +    return y1
Since `y1` is initialized as a `zeros` tensor, adding the term from the right part does not affect the final result. I changed `+=` to `=` for major code clarity.

2025-04-23 22:47 UTC, Enmartz commented
Hi, I just updated this implementation as a solver for the recovery algorithms. Please check it out @bemc22.

2025-05-14 20:27 UTC, bemc22 commented on colibri/optics/cassi.py
> +            initializer = torch.rand(shape, requires_grad=self.trainable)
uniform intitialization between [0, 1] its recommended for coded apertures.

2025-05-14 20:29 UTC, bemc22 requested changes
please could you adress the merge conflicts? @Enmartz

2025-05-24 21:04 UTC, merged