111 review and improve documentation
pycolibri/pycolibri pull request #117
Opened 2024-04-18 20:59 UTC by romanjacome99

2024-04-19 18:42 UTC, David-Morales-Norato requested changes
Here are some changes, 
In general we need to unify the notation and correct some typos

2024-04-19 18:42 UTC, David-Morales-Norato commented on colibri_hdsp/archs/e2e.py
> +        In E2E models, the optical system and the computational decoder are modeled as layers of a neural network, denoted as :math:` \forwardLinear_{\learnedOptics}` and :math:`\mathcal{N}_\theta`,
This line does not render correctly in the documentation   :math:` \forwardLinear_{\learnedOptics}`. Perhaps there is an extra space " "

2024-04-19 18:42 UTC, David-Morales-Norato commented on colibri_hdsp/archs/e2e.py
> +        In E2E models, the optical system and the computational decoder are modeled as layers of a neural network, denoted as :math:` \forwardLinear_{\learnedOptics}` and :math:`\mathcal{N}_\theta`,
Please unify notation for the reconstruction network " :math:`\mathcal{N}_\theta`" with regularizers and Models.

You can do that defining the reconstruction network in the config file of the documentations, such as \learnedOptics and  \forwardLinear is defined

2024-04-19 18:42 UTC, David-Morales-Norato commented on colibri_hdsp/archs/e2e.py
> +        where the optimal set of parameters of the optical system and the decoder are represented by :math:`\{\learnedOptics^*, \theta^*\}`. The training dataset consists of input-output pairs :math:
Use learned optics in:    `R_1(\phi)`

2024-04-19 18:42 UTC, David-Morales-Norato commented on docs/source/models.rst
>  The models module within our library provides implementations of deep learning models tailored for computational imaging tasks. These models leverage the latest advancements in neural networks to off
I think it would be nice if in this documentation we include the notation for the reconstruction network that will be used in regularizers and archs

2024-04-19 18:42 UTC, David-Morales-Norato commented on colibri_hdsp/models/unet.py
> +    Unet Model
References

2024-04-19 18:42 UTC, David-Morales-Norato commented on colibri_hdsp/models/autoencoder.py
> +    Autoencoder Model
References

2024-04-19 18:42 UTC, David-Morales-Norato commented on docs/source/regularizers.rst
> +    \{\Phi^*,\theta^*\} = \arg \min_{\Phi,\theta} \sum_{p=1}^{P}\mathcal{L}(\mathbf{x}_p, \mathcal{G}_\theta( \forwardLinear_{\learnedOptics}(\mathbf{x}_p))) + \lambda \mathcal{R}_1(\phi) + \mu \math
R_1 regularizer is duplicated

2024-04-19 18:42 UTC, David-Morales-Norato commented on docs/source/regularizers.rst
> +    \{\Phi^*,\theta^*\} = \arg \min_{\Phi,\theta} \sum_{p=1}^{P}\mathcal{L}(\mathbf{x}_p, \mathcal{G}_\theta( \forwardLinear_{\learnedOptics}(\mathbf{x}_p))) + \lambda \mathcal{R}_1(\phi) + \mu \math
H is defined as an operator, then you should use parentheses like this 'H(x)'

2024-04-19 18:42 UTC, David-Morales-Norato commented on colibri_hdsp/regularizers.py
In the regularizations of the optics, use \learnedOptics instead of "x"

In the regularization of the measurementes use "\mathbf{y}\in\yset"

2024-04-19 18:42 UTC, David-Morales-Norato commented on docs/source/regularizers.rst
> +Various regularization techniques are implemented regarding the design of optical coding elements. These regularizations force certain physical constraints on the learning parameters. Also, there are
there are typos like, "certain bhaivour onthe coded "

2024-04-22 14:27 UTC, David-Morales-Norato requested changes
Your last commit solved a few of the past comments, but there are other comments that was not addresed, I will tag you in those comments to make it more easy to track for you

2024-04-22 14:30 UTC, David-Morales-Norato commented on colibri_hdsp/archs/e2e.py
> +        In E2E models, the optical system and the computational decoder are modeled as layers of a neural network, denoted as :math:` \forwardLinear_{\learnedOptics}` and :math:`\mathcal{N}_\theta`,
Partially solved @leonsuarez24 @romanjacome99 , this is ok for now, but in the future will be better if we include a definition for the reconstruction network "\mathcal{N}_\theta". Something like "\reconstructionNetwork"

2024-04-22 14:30 UTC, David-Morales-Norato commented on colibri_hdsp/archs/e2e.py
> +        where the optimal set of parameters of the optical system and the decoder are represented by :math:`\{\learnedOptics^*, \theta^*\}`. The training dataset consists of input-output pairs :math:
Solved

2024-04-22 14:31 UTC, David-Morales-Norato commented on docs/source/models.rst
>  The models module within our library provides implementations of deep learning models tailored for computational imaging tasks. These models leverage the latest advancements in neural networks to off
Not addressed: @leonsuarez24 @romanjacome99

2024-04-22 14:31 UTC, David-Morales-Norato commented on colibri_hdsp/models/unet.py
> +    Unet Model
Not addressed @leonsuarez24 @romanjacome99

2024-04-22 14:31 UTC, David-Morales-Norato commented on colibri_hdsp/models/autoencoder.py
> +    Autoencoder Model
Not addressed @leonsuarez24 @romanjacome99

2024-04-22 14:32 UTC, David-Morales-Norato commented on docs/source/regularizers.rst
> +    \{\Phi^*,\theta^*\} = \arg \min_{\Phi,\theta} \sum_{p=1}^{P}\mathcal{L}(\mathbf{x}_p, \mathcal{G}_\theta( \forwardLinear_{\learnedOptics}(\mathbf{x}_p))) + \lambda \mathcal{R}_1(\phi) + \mu \math
Not addressed @leonsuarez24 @romanjacome99

![image](https://github.com/pycolibri/pycolibri/assets/46037413/f4aef405-9604-4ffb-bb40-f15a29786d1d)

Also, change \phi to \learnedOptics

2024-04-22 14:33 UTC, David-Morales-Norato commented on docs/source/regularizers.rst
> +    \{\Phi^*,\theta^*\} = \arg \min_{\Phi,\theta} \sum_{p=1}^{P}\mathcal{L}(\mathbf{x}_p, \mathcal{G}_\theta( \forwardLinear_{\learnedOptics}(\mathbf{x}_p))) + \lambda \mathcal{R}_1(\phi) + \mu \math
Not addressed @leonsuarez24 @romanjacome99
![image](https://github.com/pycolibri/pycolibri/assets/46037413/bb452524-32db-4a0e-a0d8-6f6300d3c64a)

2024-04-22 14:33 UTC, David-Morales-Norato commented on colibri_hdsp/regularizers.py
Not addressed @leonsuarez24 @romanjacome99

![image](https://github.com/pycolibri/pycolibri/assets/46037413/42331dd9-0703-4e2a-abf5-9c23aa1df10a)

2024-04-22 14:33 UTC, David-Morales-Norato commented on docs/source/regularizers.rst
> +Various regularization techniques are implemented regarding the design of optical coding elements. These regularizations force certain physical constraints on the learning parameters. Also, there are
Not addressed @leonsuarez24 @romanjacome99

![image](https://github.com/pycolibri/pycolibri/assets/46037413/de074175-1cd0-4fce-a71e-93f4681c4359)

2024-04-22 16:08 UTC, romanjacome99 commented on docs/source/regularizers.rst
> +    \{\Phi^*,\theta^*\} = \arg \min_{\Phi,\theta} \sum_{p=1}^{P}\mathcal{L}(\mathbf{x}_p, \mathcal{G}_\theta( \forwardLinear_{\learnedOptics}(\mathbf{x}_p))) + \lambda \mathcal{R}_1(\phi) + \mu \math
fixed

2024-04-22 16:08 UTC, romanjacome99 commented on docs/source/regularizers.rst
> +    \{\Phi^*,\theta^*\} = \arg \min_{\Phi,\theta} \sum_{p=1}^{P}\mathcal{L}(\mathbf{x}_p, \mathcal{G}_\theta( \forwardLinear_{\learnedOptics}(\mathbf{x}_p))) + \lambda \mathcal{R}_1(\phi) + \mu \math
fixed

2024-04-22 16:08 UTC, romanjacome99 commented on docs/source/regularizers.rst
> +Various regularization techniques are implemented regarding the design of optical coding elements. These regularizations force certain physical constraints on the learning parameters. Also, there are
fixed

2024-04-22 16:09 UTC, romanjacome99 commented on docs/source/models.rst
>  The models module within our library provides implementations of deep learning models tailored for computational imaging tasks. These models leverage the latest advancements in neural networks to off
check please

2024-04-22 16:09 UTC, romanjacome99 commented on colibri_hdsp/models/unet.py
> +    Unet Model
check

2024-04-22 16:09 UTC, romanjacome99 commented on colibri_hdsp/models/autoencoder.py
> +    Autoencoder Model
check

2024-04-22 21:56 UTC, David-Morales-Norato requested changes
I left the comments that were not addresed

2024-04-22 22:10 UTC, romanjacome99 commented on colibri_hdsp/regularizers.py
fixed

2024-04-22 22:11 UTC, romanjacome99 commented on colibri_hdsp/archs/e2e.py
> +        In E2E models, the optical system and the computational decoder are modeled as layers of a neural network, denoted as :math:` \forwardLinear_{\learnedOptics}` and :math:`\mathcal{N}_\theta`,
fixed!

2024-04-22 22:18 UTC, merged