133 plug and play base class implementation
pycolibri/pycolibri pull request #134
Opened 2024-06-21 12:19 UTC by bemc22

The following PR includes

* solvers module to include computational efficient solution to l2-l2 proximals
* Baseline implementation of PnP algorithm
* tests for PnP algorithm
* demo for PnP algorithm

2024-06-28 18:48 UTC, romanjacome99 requested changes

2024-06-28 18:48 UTC, romanjacome99 commented on colibri/recovery/pnp.py
> +            vtilde = self.transform.forward(vtilde)
this step is particular for sparsity prior with the DCT. I think it should be only the prox step which is performed based on the employed prior and the selected transformation if it is required. This should be implemented in the prior class.

2024-06-28 18:48 UTC, romanjacome99 commented on colibri/recovery/pnp.py
> +class PnP(nn.Module):
This class should be PnPADMM.

We can have PnPFISTA, PnPISTA, PnPHQS.

2024-06-30 02:17 UTC, bemc22 commented on colibri/recovery/pnp.py
> +            vtilde = self.transform.forward(vtilde)
solved in [d54df72]

2024-06-30 02:18 UTC, bemc22 commented on colibri/recovery/pnp.py
> +class PnP(nn.Module):
solved in [88b6c5b]

2024-07-03 16:16 UTC, David-Morales-Norato commented on examples/demo_pnp.py
> +    n_measurements  = 31**2
This amount of measurements almost freez my computer.

Not everyone have 64 Gbs in RAM

2024-07-03 20:20 UTC, bemc22 commented on colibri/recovery/fista.py
>          t = 1
Same response of https://github.com/pycolibri/pycolibri/pull/134#discussion_r1664733961

2024-07-03 20:22 UTC, bemc22 commented on colibri/recovery/pnp.py
> +            v_t    = self.prior.prox(vtilde, self._lambda)
I suggest keeping vtilde for fidelity purpose related to the mathematical formulation. Additionally, for future features like convergence residuals analysis should be useful.

2024-07-03 20:22 UTC, bemc22 commented on colibri/recovery/pnp.py
> +            u_t = u_t + x_t - v_t
I suggest keeping `u_t = u_t + x_t - v_t` for fidelity purpose related to the mathematical formulation.

2024-07-03 20:24 UTC, bemc22 commented on colibri/recovery/solvers/core.py
> +class LinearSolver(Solver):
I refer to `LinearSolver` for the explicitly computation of $y=Hx$ whiteout computational implementation tricks, other names alternatives are open to discussion.

2024-07-03 20:26 UTC, bemc22 commented on colibri/recovery/solvers/core.py
> +
I consider its not necessary since its already defined the operation in the main documentation of the class and here could be redundant.

2024-07-03 20:31 UTC, bemc22 commented on tests/test_transforms.py
> The test will be better if it is executed with random tensors rather than a single dataset image.

I suggest use a single image for educational and reproducible purposes.

2024-07-03 20:32 UTC, bemc22 commented on colibri/recovery/solvers/spc.py
> +        self.H   = acquisition_model.learnable_optics
The method `get_sensing_matrix()` of acquisition models its not implemented in this current branch.

2024-07-03 20:37 UTC, bemc22 commented on colibri/recovery/solvers/spc.py
> +class SPCSolver(Solver):
Correct, all l2-l2 formulation with linear fidelity computes the Hadj, but depending on the structure of H, we can employ efficient computational tricks. 

In the case of SPC the structure of the sensing matrix its identical along the bands/spectral dimension. In this sense we can just vectorize the spatial dimension and computes the Hadj along the spectral dimensions.

These differences are highlighted in the `SPCSolver` class (Notice that in LinearSolver the optimization variable it's a vector and in the SPCSolver the optimization variable it's a matrix).

2024-07-05 00:03 UTC, yromariogh requested changes

2024-07-05 00:03 UTC, yromariogh commented on tests/test_recovery.py
> +    rho = 0.1
why is not an input param?

2024-07-08 20:07 UTC, bemc22 commented on colibri/recovery/pnp.py
> +                error = self.fidelity.forward(x_t, y, self.H).item()
solved

2024-07-08 20:08 UTC, bemc22 commented on colibri/recovery/fista.py
>          """Runs the FISTA algorithm to solve the optimization problem.
solved

2024-07-08 20:09 UTC, bemc22 commented on docs/source/recovery.rst
solved in [a288ad2](https://github.com/pycolibri/pycolibri/pull/134/commits/a288ad27324b77d1c5d0a3549e6ee8a30f9c661d)

2024-07-08 20:09 UTC, bemc22 commented on colibri/recovery/fista.py
solved in [a288ad2](https://github.com/pycolibri/pycolibri/pull/134/commits/a288ad27324b77d1c5d0a3549e6ee8a30f9c661d)

2024-07-08 20:09 UTC, bemc22 commented on colibri/recovery/fista.py
> +        self.H = lambda alpha: self.acquistion_model.forward(alpha)
solved in [a288ad2](https://github.com/pycolibri/pycolibri/pull/134/commits/a288ad27324b77d1c5d0a3549e6ee8a30f9c661d)

2024-07-08 20:11 UTC, bemc22 commented on colibri/recovery/fista.py
> +            x = z - self.alpha * self.fidelity.grad(z, y, self.H)
i dont understand the question, fidelity.grad internally assign `requires_grad` for z

2024-07-08 20:12 UTC, bemc22 commented on colibri/recovery/fista.py
> +    def __init__(self, fidelity, prior, acquistion_model, max_iters=5, alpha=1e-3, _lambda=0.1):
solved in [a288ad2](https://github.com/pycolibri/pycolibri/pull/134/commits/a288ad27324b77d1c5d0a3549e6ee8a30f9c661d)

2024-07-08 20:12 UTC, bemc22 commented on colibri/recovery/fista.py
>          """Initializes the Fista class.
solved in [a288ad2](https://github.com/pycolibri/pycolibri/pull/134/commits/a288ad27324b77d1c5d0a3549e6ee8a30f9c661d)

2024-07-08 20:12 UTC, bemc22 commented on colibri/recovery/fista.py
>                  print("Iter: ", i, "fidelity: ", error)
solved in [a288ad2](https://github.com/pycolibri/pycolibri/pull/134/commits/a288ad27324b77d1c5d0a3549e6ee8a30f9c661d)

2024-07-08 20:12 UTC, bemc22 commented on colibri/recovery/fista.py
>          return x_hat
solved in [a288ad2](https://github.com/pycolibri/pycolibri/pull/134/commits/a288ad27324b77d1c5d0a3549e6ee8a30f9c661d)

2024-07-08 20:12 UTC, bemc22 commented on docs/source/recovery.rst
>      colibri.recovery.fista.Fista
solved in [a288ad2](https://github.com/pycolibri/pycolibri/pull/134/commits/a288ad27324b77d1c5d0a3549e6ee8a30f9c661d)

2024-07-08 20:12 UTC, bemc22 commented on colibri/recovery/pnp.py
> +    r"""
solved in [a288ad2](https://github.com/pycolibri/pycolibri/pull/134/commits/a288ad27324b77d1c5d0a3549e6ee8a30f9c661d)

2024-07-08 20:18 UTC, bemc22 commented on colibri/recovery/pnp.py
> +    Plug-and-Play (PnP) algorithm for solving the optimization problem based on the Alternating Direction Method of Multipliers (ADMM) formulation.
solved in [a288ad2](https://github.com/pycolibri/pycolibri/pull/134/commits/a288ad27324b77d1c5d0a3549e6ee8a30f9c661d)

2024-07-08 20:19 UTC, bemc22 commented on colibri/recovery/pnp.py
> +        return x_hat
solved in [a288ad2](https://github.com/pycolibri/pycolibri/pull/134/commits/a288ad27324b77d1c5d0a3549e6ee8a30f9c661d)

2024-07-08 20:19 UTC, bemc22 commented on colibri/recovery/solvers/core.py
> +            \min_{\textbf{x}} \frac{1}{2}||\textbf{y} - \textbf{H}\textbf{x}||_2^2 + \rho||\textbf{x} - \tilde{\textbf{x}}||_2^2
i suggest proposing this as a separate PR

2024-07-08 20:23 UTC, bemc22 commented on colibri/recovery/solvers/core.py
> +            acquisition_model (BaseOpticsLayer): Acquisition model
solved in [a288ad2](https://github.com/pycolibri/pycolibri/pull/134/commits/a288ad27324b77d1c5d0a3549e6ee8a30f9c661d)

2024-07-08 20:23 UTC, bemc22 commented on colibri/recovery/solvers/spc.py
> +        where :math:`\textbf{X}` is the tensor to be recovered, :math:`\textbf{Y}` is the input tensor,
solved in [a288ad2](https://github.com/pycolibri/pycolibri/pull/134/commits/a288ad27324b77d1c5d0a3549e6ee8a30f9c661d)

2024-07-08 20:26 UTC, bemc22 commented on colibri/optics/functional.py
>          torch.Tensor: Reconstructed image tensor of size (B, L, M, N).
solved in [a288ad2](https://github.com/pycolibri/pycolibri/pull/134/commits/a288ad27324b77d1c5d0a3549e6ee8a30f9c661d)

2024-07-08 20:30 UTC, bemc22 commented on examples/demo_pnp.py
> +    n_measurements  = 31**2
solved in [a288ad2](https://github.com/pycolibri/pycolibri/pull/134/commits/a288ad27324b77d1c5d0a3549e6ee8a30f9c661d)

2024-07-08 20:31 UTC, bemc22 commented on colibri/recovery/pnp.py
> +            acquistion_model (nn.Module): The acquisition model of the imaging system. This is a function that models the process of data acquisition in the imaging system.
what is the typo?

2024-07-08 20:32 UTC, bemc22 commented on colibri/recovery/pnp.py
> +            rho (float): The penalty parameter for the ADMM formulation. Defaults to 0.1.
yes, the name lambda its reserved for anonymous functions, i.e

```python
add_func: lambda x,y: x + y
```

2024-07-08 20:33 UTC, bemc22 commented on colibri/recovery/pnp.py
> +            x0 (torch.Tensor, optional): The initial guess for the solution. Defaults to None.
agree

2024-07-08 20:34 UTC, bemc22 commented on colibri/recovery/pnp.py
> +            GradientDescent = lambda x, xt: x - self.alpha * self.fidelity.grad(x, y, self.H)  - self.rho * (x - xt)
nothing, the purpose is to not overuse the same local variable for anonymous functions and the local method

2024-07-08 20:35 UTC, bemc22 commented on colibri/recovery/pnp.py
> +            x_t    = x_solver(xtilde, self.rho) if self.solver == "close" else x_solver(x_t, xtilde)
for me its clear

2024-07-08 20:36 UTC, bemc22 commented on colibri/recovery/solvers/core.py
> +            y (torch.Tensor): Input tensor with shape (B, *)
This means whatever amount of dims (i.e, (B, N1, N2, ...) ) its the common notation used in pytorch docs.

2024-07-08 20:37 UTC, bemc22 commented on colibri/recovery/solvers/spc.py
> +        Hadj = torch.inverse(Hadj)
In fact the final computation its Hadj, rename line 50 introduce additional memory

2024-07-08 20:38 UTC, bemc22 commented on colibri/recovery/terms/fidelity.py
>              x (torch.Tensor): The image to be reconstructed.
y was renamed

2024-07-08 20:38 UTC, bemc22 commented on examples/demo_pnp.py
> +x_hat -= x_hat.min()
for visualization

2024-07-08 20:38 UTC, bemc22 commented on examples/demo_fista.py
> +fidelity  = L2()
For the moment there is no other options implemented

2024-07-08 20:38 UTC, bemc22 commented on colibri/optics/functional.py
> +    Hinv   = torch.pinverse(H) if pinv else torch.transpose(H, 0, 1)
I dont undestand why

2024-07-08 20:39 UTC, bemc22 commented on colibri/recovery/solvers/core.py
> +        Hadj = torch.inverse(Hadj)
i open to suggestions

2024-07-08 20:40 UTC, bemc22 commented on colibri/recovery/terms/prior.py
> +            self.transform = None
Because exits explicit regularizations on the natural signal domain ( i.e, denoising regularization )

2024-07-08 20:41 UTC, bemc22 commented on tests/test_recovery.py
> +    rho = 0.1
this is for testing, its a fixed parameter

2024-07-08 23:10 UTC, David-Morales-Norato requested changes
I finish this review iteration. We are almost there, but there are a few comments that needs to be addressed

2024-07-08 23:10 UTC, David-Morales-Norato commented on colibri/recovery/solvers/spc.py
> +class SPCSolver(Solver):
> Correct, all l2-l2 formulation with linear fidelity computes the Hadj, but depending on the structure of H, we can employ efficient computational tricks.
> 
> In the case of SPC the structure of the sensing matrix its identical along the bands/spectral dimension. In this sense we can just vectorize the spatial dimension and computes the Hadj along the spectral dimensions.
> 
> These differences are highlighted in the `SPCSolver` class (Notice that in LinearSolver the optimization variable it's a vector and in the SPCSolver the optimization variable it's a matrix).

That math difference should be explicit in the documentation of the `SPCSolver` class

2024-07-08 23:10 UTC, David-Morales-Norato commented on colibri/recovery/solvers/spc.py
> +        where :math:`\textbf{X}` is the tensor to be recovered, :math:`\textbf{Y}` is the input tensor,
The shapes in the documentation are not rendered correctly.

![image](https://github.com/pycolibri/pycolibri/assets/46037413/40b14e9e-6b00-41e4-8016-a0f53691d1bf)

2024-07-08 23:10 UTC, David-Morales-Norato commented on colibri/recovery/solvers/spc.py
> +        self.H   = acquisition_model.learnable_optics
Thanks. I will create an issue to implement them

2024-07-08 23:10 UTC, David-Morales-Norato commented on colibri/recovery/pnp.py
> +            \underset{\mathbf{x}}{\text{min}} \quad \frac{1}{2}||\mathbf{y} - \forwardLinear (\mathbf{x})||^2 + \lambda||\mathbf{x}||_1
@bemc22 Not solved

2024-07-08 23:10 UTC, David-Morales-Norato commented on colibri/recovery/solvers/spc.py
> +        Hadj = torch.matmul(self.H.permute(1, 0), self.H) + rho * torch.eye(self.H.shape[1])
@bemc22 Not solved

2024-07-09 14:24 UTC, bemc22 commented on colibri/recovery/solvers/core.py
> +
Agreed, I will uniform the documentation between al solvers classes

2024-07-09 19:00 UTC, bemc22 commented on colibri/recovery/terms/fidelity.py
> +        r""" Computes the L1 fidelity term.
solved

2024-07-09 19:19 UTC, bemc22 commented on colibri/recovery/pnp.py
> +
agree

2024-07-09 19:20 UTC, bemc22 commented on colibri/recovery/solvers/spc.py
> +        where :math:`\textbf{X}` is the tensor to be recovered, :math:`\textbf{Y}` is the input tensor,
done

2024-07-09 19:43 UTC, David-Morales-Norato commented on colibri/recovery/fista.py
>          t = 1
to later discussion

2024-07-09 20:17 UTC, David-Morales-Norato approved these changes
My comments have been addressed. I consider that this PR is ready to be merged into the main branch.

2024-07-09 20:54 UTC, yromariogh requested changes

2024-07-09 20:54 UTC, yromariogh commented on colibri/recovery/solvers/spc.py
> +        super(SPCL2L2Solver, self).__init__(y, acquisition_model)
Change it for SPC_L2L2_Solver

2024-07-13 22:47 UTC, merged