Update dataset lecture
pycolibri/pycolibri pull request #135
Opened 2024-06-30 20:48 UTC by Enmartz

This is a new version of the dataset lecture for Colibri repository.

2024-07-02 18:07 UTC, romanjacome99 commented
Please create a demo_dataset.py

2024-07-05 21:59 UTC, leonsuarez24 commented on examples/demo_datasets.py
> +from torch.utils import data
Write it below %% so the interactive window works

2024-07-05 21:59 UTC, leonsuarez24 commented on examples/demo_datasets.py
> +from colibri.data.datasets import CustomDataset
add before this line

import os
os.chdir(os.path.dirname(os.getcwd()))

to change the directory of the demo folder to the principal folder

2024-07-05 22:20 UTC, leonsuarez24 commented on examples/demo_datasets.py
> +from torch.utils import data
add this line after %% so the interactive window can detected when you run the cell
![image](https://github.com/pycolibri/pycolibri/assets/138550157/dd7e539a-71dc-4970-bd0b-ef97d76a423e)

2024-07-05 22:34 UTC, leonsuarez24 commented on colibri/data/datasets.py
> +class CustomDataset(Dataset):
add in this documentation all the available datasets ( 'mnist',  'fashion_mnist', 'cifar10', 'cifar100') to avoid users looking in other files what are the available datasets 

also add that there is available  readers for cave and arad datasets

2024-07-05 22:42 UTC, leonsuarez24 commented
update datasets.rst and mention there the available datasets

2024-07-05 22:47 UTC, leonsuarez24 commented on examples/demo_colibri.py
> +name = 'cifar10'
add a comment with the available datasets similar to the one you mention belowe to the adquisicon systems (adquistion_name = 'c_cassi'  # ['spc', 'cassi'])

2024-07-05 22:49 UTC, leonsuarez24 commented
maybe in the demo you could also show how the data readers work for not built in datasets

2024-07-07 03:11 UTC, Enmartz commented on colibri/data/datasets.py
> +class CustomDataset(Dataset):
solved

2024-07-07 03:12 UTC, Enmartz commented on examples/demo_colibri.py
> +name = 'cifar10'
solved

2024-07-07 03:13 UTC, Enmartz commented on examples/demo_datasets.py
> +from torch.utils import data
solved

2024-07-07 03:13 UTC, Enmartz commented on examples/demo_datasets.py
> +from colibri.data.datasets import CustomDataset
solved

2024-07-07 21:29 UTC, Enmartz commented
> maybe in the demo you could also show how the data readers work for not built in datasets

The cave dataset was added to the demo example

2024-07-08 15:10 UTC, leonsuarez24 commented on examples/demo_datasets.py
> +    plt.scatter(coord2[1], coord2[0], s=120, edgecolors='black')
maybe you could add axis titles to the signature plot

2024-07-08 15:16 UTC, leonsuarez24 commented
couldn't find in the docs 
![image](https://github.com/pycolibri/pycolibri/assets/138550157/b6635214-a6bb-4fd4-af76-e6ae9d53a2b5)

2024-07-08 15:17 UTC, leonsuarez24 commented
i think it would be great if you could include in the docs the documentation of the class CustomDataset

2024-07-08 23:03 UTC, Enmartz commented
> couldn't find BASIC_DATASETS in the docs ![image](https://private-user-images.githubusercontent.com/138550157/346619431-b6635214-a6bb-4fd4-af76-e6ae9d53a2b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0Nzg2NjAsIm5iZiI6MTcyMDQ3ODM2MCwicGF0aCI6Ii8xMzg1NTAxNTcvMzQ2NjE5NDMxLWI2NjM1MjE0LWE2YmItNGZkNC1hZjc2LWU2YWU5ZDUzYTJiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQyMjM5MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjVjYWIyYjUwZmY3YWIwOGEwOTRhYmZkNmUwMTBkMWFkNWU1ZTNlMmVkY2I0OTM1MjIxYWUzYjQyNzBiYjgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H6CW--y8fDvu0YwnSqviZIAC2MFcfX6QuMsuu6ZqpnI)

Solved!

2024-07-09 18:58 UTC, bemc22 requested changes

2024-07-09 19:02 UTC, Enmartz commented on README.md
> +from colibri.data.datasets_ import Dataset
solved

2024-07-09 19:06 UTC, Enmartz commented on README.md
> +adquistion_name = 'cassi'  # ['spc', 'cassi']
solved

2024-07-09 19:08 UTC, Enmartz commented on colibri/data/datasets.py
> +DATASET_READER = {
`D` are the functions that come from `data/utils.py`. You can find it at the beginning of this script:

![image](https://github.com/pycolibri/pycolibri/assets/58752635/3f228d34-f312-4f4f-9fba-c498f4df3183)

2024-07-09 20:08 UTC, bemc22 approved these changes

2024-07-09 20:22 UTC, merged