124 doe applications
pycolibri/pycolibri pull request #136
Opened 2024-07-02 16:49 UTC by David-Morales-Norato

2024-07-06 13:08 UTC, Enmartz commented on colibri/optics/sota_does.py
> +        N: Number of pixels
N is a nonexistent variable, It must be split into `nx` and `ny`, respectively.

2024-07-06 13:39 UTC, Enmartz commented on colibri/optics/sota_does.py
> +def fresnel_lens(ny: int, nx: int, focal = None, radius = None):
This code allows the creation of non-square Fresnel lenses. I think all optics should only work with square dimensions to maintain realism.

2024-07-06 13:47 UTC, Enmartz commented on colibri/optics/functional.py
> +    Generate spatial coordinates for wave optics simulations in either Cartesian or polar format.
This description should be: Generate coordinates for wave optics simulations in the Cartesian or polar coordinate system.

2024-07-06 13:47 UTC, Enmartz commented on colibri/optics/functional.py
> +        pixel_size (float): Pixel pixel_size in meters.
pixel_size (float): Pixel size in meters.

2024-07-06 13:53 UTC, Enmartz commented on colibri/optics/sota_does.py
> +def spiral_doe(ny: int, nx: int, number_spirals: int, radius: float, focal: float, start_w = 450e-9, end_w = 650e-9):
It would be good to write a simple mathematical description of this function if possible.

2024-07-06 13:54 UTC, Enmartz commented on colibri/optics/sota_does.py
If possible, it would be good to write a simple mathematical description of all functions.

2024-07-06 14:20 UTC, Enmartz commented on colibri/optics/sota_does.py
> +    height_map = -(r**2)/(focal)
Theoretical question: why is the height map calculated like this? It would be nice if this could be briefly explained in the description of this feature.

2024-07-06 14:22 UTC, Enmartz commented on examples/demo_does.py
> +ax[1].imshow(aperture, cmap="plasma")
These images should have a title.

2024-07-06 14:30 UTC, Enmartz commented on colibri/optics/functional.py
> +    where :math:`\lambda` is the wavelength.
This is not well compiled in the documentation, please check.

2024-07-06 14:53 UTC, Enmartz commented on colibri/optics/functional.py
> +        field (torch.Tensor): Input optical field. Shape (len(wavelengths), nu, nv).
`nu` and `nv` are not defined

2024-07-06 14:57 UTC, Enmartz commented on colibri/optics/functional.py
> +        nv (int): Resolution at Y axis in pixels.
There is an ambiguity between the use of `nx` and `ny` with `nu` and `nv`. It should be clarified.

2024-07-06 14:57 UTC, Enmartz commented on colibri/optics/functional.py
> +        nv (int): Resolution at Y axis in pixels.
For this and the function `transfer_function_angular_spectrum`

2024-07-06 14:58 UTC, Enmartz commented on colibri/optics/functional.py
There is an ambiguity between the use of `nx` and `ny` with `nu` and `nv`. It should be clarified.

2024-07-06 15:20 UTC, Enmartz commented on colibri/optics/functional.py
> +    where :math:`f` is the input image, :math:`h` is the PSF, :math:`g` is the convolved output, :math:`\mathcal{F}` and :math:`\mathcal{F}^{-1}` denote the Fourier and inverse Fourier transforms.
These equations were not well compiled.

2024-07-06 15:21 UTC, Enmartz commented on colibri/optics/functional.py
> +    g = \mathcal{F}^{-1}(\mathcal{F}(f) * \mathcal{F}(h))
These equations were not well compiled.

2024-07-06 15:22 UTC, Enmartz commented on colibri/optics/functional.py
> +    This function applies the convolution of an image with a Point Spread Function (PSF).
This description was not well compiled.

2024-07-06 15:28 UTC, Enmartz commented on colibri/optics/doe.py
> +class SingleDOESpectral(BaseOpticsLayer):
I think this layer should be called SingleDOE, without Spectral, as a more general layer.

2024-07-06 15:28 UTC, Enmartz commented on colibri/optics/doe.py
> +    Mathematically, this systems can be described as follows.
this system*

2024-07-06 15:29 UTC, Enmartz commented on colibri/optics/doe.py
> +    Mathematically, this systems can be described as follows.
follows: *

2024-07-06 15:32 UTC, Enmartz commented on colibri/optics/doe.py
> +                        pixel_size,
These parameters should be optional so that by default a simple representation is generated, which is described in the documentation. Just as it was done for the `height_map`. The main idea is to make it easier for the user to implement this layer so that they can use it without having problems.

2024-07-06 15:34 UTC, Enmartz commented on colibri/optics/doe.py
> +    def forward_convolution(self, x, height_map):
This function is redundant with `forward` function.

2024-07-06 15:46 UTC, Enmartz commented on colibri/optics/functional.py
> +def psf_single_doe_spectral(height_map: torch.Tensor, aperture: torch.Tensor, refractive_index: callable,
This function should be called `psf_single_doe`

2024-07-06 15:49 UTC, Enmartz commented on colibri/optics/functional.py
> +def addGaussianNoise(y: torch.Tensor, snr: float):
Set the name of this function from camel case `addGaussianNoise` to pythonic case `add_gaussian_noise`

2024-07-06 15:49 UTC, Enmartz commented on colibri/optics/functional.py
> +    n ~ N(0, \sigma^2)
These equations were not well compiled

2024-07-06 15:50 UTC, Enmartz commented on colibri/optics/functional.py
> +        \end{cases}
It is necessary to indicate what the output or operator is. It would also be good to indicate which is the region in which (x, y) operates, whether from [-x, x] or from [0, x_max], the same for y.

2024-07-06 15:52 UTC, Enmartz commented on colibri/optics/functional.py
> +    I = \frac{1}{L} \sum_{\lambda} I_{\lambda}
This equation was not well compiled

2024-07-06 15:54 UTC, Enmartz commented on colibri/optics/functional.py
> +def get_space_coords(ny: int, nx: int, pixel_size: float, device=torch.device('cpu'), type='cartesian'):
The description should contain a brief mathematical description of what coordinates are generating, and show both cases, "cartesian" and "polar".

2024-07-06 16:00 UTC, Enmartz commented on examples/demo_does.py
> +type_doe = "fresnel_lens" # spiral, fresnel_lens
I suggest to change this for spiral because it is more visual for this example for the cifar10 dataset

2024-07-06 16:01 UTC, Enmartz commented on examples/demo_does.py
> +type_wave_propagation = "angular_spectrum" # fresnel, angular_spectrum, fraunhofer
Fraunhofer is not implemented, I suggest to remove it from the comment in this line

2024-07-06 16:03 UTC, Enmartz commented on colibri/optics/functional.py
> +        approximation (str): Approximation (or diffraction model type) to use, can be "fresnel", "angular_spectrum" or "fraunhofer".
Fraunhofer is implemented but it is not being used here

2024-07-06 16:09 UTC, Enmartz requested changes
It's a really good improvement for the repository! Thanks for the hard work. As a reviewer, I left you some comments to further improve the documentation and the use of some functions.

2024-07-06 17:59 UTC, David-Morales-Norato commented on colibri/optics/sota_does.py
> +        N: Number of pixels
solved

2024-07-06 18:07 UTC, David-Morales-Norato commented on colibri/optics/functional.py
> +    Generate spatial coordinates for wave optics simulations in either Cartesian or polar format.
solved

2024-07-06 18:07 UTC, David-Morales-Norato commented on colibri/optics/functional.py
> +        pixel_size (float): Pixel pixel_size in meters.
solved

2024-07-06 18:31 UTC, David-Morales-Norato commented on colibri/optics/sota_does.py
> +def fresnel_lens(ny: int, nx: int, focal = None, radius = None):
You are correct. 

The height map is from a conventional lens. Therefore I will change the name to this to improve the comprehension

However, it is important to remark that computationally, both **height maps** are the same **phase** due to the $2\pi$-periodic and wrapping behavior of $\exp(i \cdot \phi_{})$.

2024-07-06 18:42 UTC, David-Morales-Norato commented on colibri/optics/sota_does.py
> +    height_map = -(r**2)/(focal)
That is the traditional equation of a conventional lens. The equation is a spherical curvature of (focal) $f$

2024-07-06 18:45 UTC, David-Morales-Norato commented on examples/demo_does.py
> +ax[1].imshow(aperture, cmap="plasma")
solved

2024-07-06 18:49 UTC, David-Morales-Norato commented on colibri/optics/functional.py
> +    where :math:`\lambda` is the wavelength.
solved

2024-07-06 18:53 UTC, David-Morales-Norato commented on colibri/optics/functional.py
> +        field (torch.Tensor): Input optical field. Shape (len(wavelengths), nu, nv).
solved

2024-07-06 19:05 UTC, David-Morales-Norato commented on colibri/optics/functional.py
You are right, besides it is not consistent with the chosen notation of $(B, C, M, N)$ sizes of spectral images. Therefore we have changed these sizes.

2024-07-06 19:11 UTC, David-Morales-Norato commented on colibri/optics/functional.py
> +    g = \mathcal{F}^{-1}(\mathcal{F}(f) * \mathcal{F}(h))
solved

2024-07-06 19:14 UTC, David-Morales-Norato commented on colibri/optics/functional.py
> +    This function applies the convolution of an image with a Point Spread Function (PSF).
solved

2024-07-06 19:16 UTC, David-Morales-Norato commented on colibri/optics/doe.py
> +class SingleDOESpectral(BaseOpticsLayer):
The problem is that it is not general. It will only work for DOEs for spectral applications. 

For Depth and other applications, the math and code is different.

2024-07-06 19:17 UTC, David-Morales-Norato commented on colibri/optics/doe.py
> +    Mathematically, this systems can be described as follows.
solved

2024-07-06 19:37 UTC, David-Morales-Norato commented on colibri/optics/doe.py
> +                        pixel_size,
solved

2024-07-06 19:40 UTC, David-Morales-Norato commented on colibri/optics/doe.py
> +    def forward_convolution(self, x, height_map):
This function is not redundant because the forward has the `type_calculation` argument used to choose forward_convolution or `deconvolution`. 

But to improve comprehension, I have changed to just `convolution`

2024-07-06 19:41 UTC, David-Morales-Norato commented on colibri/optics/functional.py
> +def psf_single_doe_spectral(height_map: torch.Tensor, aperture: torch.Tensor, refractive_index: callable,
Not because only works for spectral

2024-07-06 20:01 UTC, David-Morales-Norato commented on colibri/optics/functional.py
> +        \mathcal{G}(f_x, f_y) = \mathcal{F}(f_x, f_y) * \mathcal{H}(f_x, f_y)
Solved

2024-07-06 20:02 UTC, David-Morales-Norato commented on colibri/optics/functional.py
> +def addGaussianNoise(y: torch.Tensor, snr: float):
Thanks, solved

2024-07-06 20:02 UTC, David-Morales-Norato commented on colibri/optics/functional.py
> +    n ~ N(0, \sigma^2)
solved

2024-07-06 20:11 UTC, David-Morales-Norato commented on colibri/optics/functional.py
> +        \end{cases}
Solved

2024-07-06 20:11 UTC, David-Morales-Norato commented on colibri/optics/functional.py
x and y are spatial coordinates, they are not bounded

2024-07-06 20:12 UTC, David-Morales-Norato commented on colibri/optics/functional.py
> +    I = \frac{1}{L} \sum_{\lambda} I_{\lambda}
solved

2024-07-06 20:16 UTC, David-Morales-Norato commented on examples/demo_does.py
> +type_doe = "fresnel_lens" # spiral, fresnel_lens
solved

2024-07-06 20:16 UTC, David-Morales-Norato commented on colibri/optics/functional.py
> +def get_space_coords(ny: int, nx: int, pixel_size: float, device=torch.device('cpu'), type='cartesian'):
I have improved the documentation of the function. But,  I think this concept is not that hard to understand. That is a math concept of high school.

2024-07-06 20:19 UTC, David-Morales-Norato commented on examples/demo_does.py
> +type_wave_propagation = "angular_spectrum" # fresnel, angular_spectrum, fraunhofer
Of course it is implemented, see the propagators list

2024-07-06 20:21 UTC, David-Morales-Norato commented on colibri/optics/functional.py
> +        approximation (str): Approximation (or diffraction model type) to use, can be "fresnel", "angular_spectrum" or "fraunhofer".
Because the DOE PSF model needs near-field propagation. Not far field. But we have implemented the Fraunhofer approximation because it was a low effort to future implementations of other systems (depth DOEs, phase retrieval)

2024-07-06 20:22 UTC, David-Morales-Norato commented on colibri/optics/sota_does.py
> +def fresnel_lens(ny: int, nx: int, focal = None, radius = None):
I disagree with the restriction to square optics. (That is not necessary real).

2024-07-06 20:30 UTC, David-Morales-Norato commented
> It's a really good improvement for the repository! Thanks for the hard work. As a reviewer, I left you some comments to further improve the documentation and the use of some functions.

Thank you for your exhaustive review, the code and documentation have improved. 

I have addressed all your comments and questions with the necessary changes. Please take a look at my responses and let me know if you have any additional requests or if the PR is ready to be merged.

2024-07-07 23:25 UTC, Enmartz commented on colibri/optics/functional.py
Yes, but I mean, in terms of implementation, it would be nice if we could tell the user what the operating discrete range is.

2024-07-07 23:29 UTC, Enmartz commented on examples/demo_does.py
> +type_wave_propagation = "angular_spectrum" # fresnel, angular_spectrum, fraunhofer
I mean, It is not implementing in the function where it is called. Then, I get the following error when I set  the following line `type_wave_propagation = "fraunhofer" # fresnel, angular_spectrum, fraunhofer` from the `demo_does.py`.

![image](https://github.com/pycolibri/pycolibri/assets/58752635/ba811470-972c-4dbc-b8e4-b3539cc416b8)

2024-07-07 23:30 UTC, Enmartz requested changes
I left you some minor comments, please review them, thanks.

2024-07-08 16:44 UTC, David-Morales-Norato commented on colibri/optics/functional.py
You are right. I have included this description in get  `get_space_coords`

2024-07-08 18:44 UTC, David-Morales-Norato commented on colibri/optics/functional.py
solved

2024-07-08 18:44 UTC, David-Morales-Norato commented on examples/demo_does.py
> +type_wave_propagation = "angular_spectrum" # fresnel, angular_spectrum, fraunhofer
At some point the code to use that case was deleted by mistake. 

I restored the code. 

Solved

2024-07-08 19:23 UTC, David-Morales-Norato commented
> I left you some minor comments, please review them, thanks.

I have solved your comments

2024-07-08 22:35 UTC, Enmartz approved these changes

2024-07-08 23:11 UTC, romanjacome99 commented on colibri/optics/functional.py
> +def get_space_coords(ny: int, nx: int, pixel_size: float, device=torch.device('cpu'), type='cartesian'):
It's a minor thing, but it should be `get_spatial_coords`

2024-07-08 23:22 UTC, romanjacome99 commented on colibri/optics/functional.py
> +    result =  ifft(field / pixel_size**2 / c)
according to the equation  $U_0(x,y) \approx  \frac{1}{j\lambda z} e^{j k z} e^{\frac{j k (x^2 + y^2)}{2z}} \mathcal{F}^{-1}\{ U(x,y) \}$ but the code implements $\mathcal{F}^{-1}\left(\frac{U(x,y)}{( \frac{1}{j\lambda z} e^{j k z} e^{\frac{j k (x^2 + y^2)}{2z}}) }\right)$ I don't know if I am confused with the equation.

2024-07-08 23:28 UTC, romanjacome99 commented on colibri/optics/functional.py
> +def add_pad(x, pad):
This function  and  `unpadd` does not appear in the docs. Please check

2024-07-09 14:26 UTC, David-Morales-Norato commented on colibri/optics/functional.py
> +def add_pad(x, pad):
Thanks, solved

2024-07-09 14:40 UTC, David-Morales-Norato commented on colibri/optics/functional.py
> +    result =  ifft(field / pixel_size**2 / c)
The Franhoufer propagation can be described as the operator

$P_{\text{Franhoufer}}: \mathcal{X_0} \rightarrow \mathcal{X_z}$
$U(x, y, z) = P_{\text{Franhoufer}}(U(x, y, 0))$
$U(x,y, z) \approx  \frac{1}{j\lambda z} e^{j k z} e^{\frac{j k (x^2 + y^2)}{2z}} \mathcal{F} \( U(x,y, 0)  \)$

And for some applications we require an inverse propagator  $P_{\text{Franhoufer}}^{-1}: \mathcal{X_z} \rightarrow \mathcal{X_0}$ such that 

$U(x, y, 0) = P_{\text{Franhoufer}}^{-1}(P_{\text{Franhoufer}}(U(x, y, 0)))$


that is $U(x,y, z=0)  \approx \mathcal{F}^{-1}\left(\frac{U(x,y, z)}{( \frac{1}{j\lambda z} e^{j k z} e^{\frac{j k (x^2 + y^2)}{2z}}) }\right)$

The code that you are highlighting is the code of the inverse franhoufer propagation.



pd: For ASM and Fresnel the inversion is just to use (-z) as propagation distance. But in franhouber this is not possible due strong approximations, so we had to implement a different function

2024-07-09 18:51 UTC, merged